name: autoparts_shop

description: "Auto parts"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utilities
  intl: ^0.20.2
  csv: ^5.0.2
  path_provider: ^2.1.1
  pdf: ^3.11.1
  share_plus: ^10.0.0

  # UI
  flutter_slidable: ^3.0.1

  # Image picker
  image_picker: ^1.0.4

  # Input Mask --- NEW

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/database/autoparts.db
